
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    environment:
      - ENV=production
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
